### ISSUE TITLE
MYPET Problem/RPGInv Integration 

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#102]
I have a WITHER MyPet. Upon Startup of the server(after restarting the server) I get this in the console.

[22:35:42 WARN]: [RPGInventory] Pet 'WITHER' can't be added: No enum constant ru.endlesscode.rpginventory.pet.PetType.Role.MYPET

Assuming it doesn't support the Wither, or stuff like EnderDragon as custom pets, so it doesn't make an egg for the pet at all.

**Comment by OsipXD** [comment]
Can you provide me you starplugin loading logs?

**Comment by KnifeKat** [comment]
I messed up the config file, that was my fault.
