### ISSUE TITLE
You must allow downloading the resource-pack!

### ISSUE THREAD

**Issue by aaTking** [EndlessCodeGroup/RPGInventory#103]
What should I do?
Client version 1.12.1

**Comment by OsipXD** [comment]
Hello!
Please, make sure that you've configured and enabled plugin

**Comment by aaTking** [comment]
Yes, I'm sure the plug-in has been enabled. But there is a hint

You must allow downloading the resource-pack!

**Comment by OsipXD** [comment]
Have you read FAQ? And have you any errors in logs?

**Comment by aaTking** [comment]
emmm... Yes, I've read it. The question seems to be that the client is prevented from downloading, but I don't know how to set it up

**Comment by OsipXD** [comment]
Have you warnings in log?

**Comment by KnifeKat** [comment]
@aaTking - I have a solution that works for this 100%. Wait until Wednesday afternoon. I'll be posting a Guide for the entire usage of RPGInventory.

@OsipXD  - Check your PMs on Spigot that I sent you. You'll be quite impressed with the bit of work I've done for your page. Thank you in advance.

**Comment by osipxd** [comment]
Closed. Create new issue if problem still here
