### ISSUE TITLE
conditions bug

### ISSUE THREAD

**Issue by aaTking** [EndlessCodeGroup/RPGInventory#104]
When using the skillapi's usage conditions
Conflicts with this plugin
Cause the infinite brush
I hope I can replace it with lore to determine if I'm fit
That's the perfect solution
Looking forward to the update

**Comment by KnifeKat** [comment]
SkillAPI does not have full compatibility with RPGInventory at this current moment in time. We suggest you contact the author of SkillAPI and have them add compatibility with RPGInventory until we're able to add some compatibility of our own. We apologize in advance and have a wonderful afternoon!

Join our Discord so we can help you with additional issues in the future. =)

**Comment by aaTking** [comment]
Can't remove the condition check of armor and deputy,
Because the armor items generated by the plug-in are not allowed to change the lore,
The equipment is poor in richness
But if written in other plug-in equipment conditions, such as other plug-ins wear limit level
Brush items would conflict with this plug-in.
:)
