### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to RPGInventory v2.1.4

### ISSUE THREAD

**Issue by Fargus5** [EndlessCodeGroup/RPGInventory#105]
Hi osipXD please to find below the error occurred

https://github.com/BalrogGames/herosfaith/issues/12

could you be so kind to fix this?

**Comment by OsipXD** [comment]
Thanks for report, I'll fix it

**Comment by Fargus5** [comment]
Has been fixed?

**Comment by Dereku** [comment]
Lel. It's autoclosed. Anyway you can build the plugin and check it out.

**Comment by Fargus5** [comment]
What do you mean?

**Comment by Fargus5** [comment]
?

**Comment by OsipXD** [comment]
It was closed from commit.
You can build plugin from sources or wait update
