### ISSUE TITLE
Pet duplication after teleportation

### ISSUE THREAD

**Issue by aaTking** [EndlessCodeGroup/RPGInventory#110]
The horse was teleported
There will be one more horse

BetonQuest Plug-in to teleported

**Comment by OsipXD** [comment]
I don't understand you.

**Comment by aaTking** [comment]
When using this plugin.
There are some possibility that will generate an extra horse at old location when a player teleport with a horse.
Not every time but it should be a bug

**Comment by OsipXD** [comment]
Can you provide step-by-step guide to 100% reproduce it?

**Comment by aaTking** [comment]
![image](https://user-images.githubusercontent.com/34217827/34586598-950649ce-f1df-11e7-9469-43563cd91de6.png)
This NPC is teleport, and I use the bq plugin to send it, and then I come back and see it, and I get one more

**Comment by Dereku** [comment]
Pet duplication after teleportation \\:D/

**Comment by KnifeKat** [comment]
Wouldn't this be a BetonQuest issue, then?

**Comment by aaTking** [comment]
I don't think so.
We should be more proactive in solving any problems.
Rather than waiting for other authors to be compatible.
