### ISSUE TITLE
LoreAttributeRecoded Request

### ISSUE THREAD

**Issue by georgegxb** [EndlessCodeGroup/RPGInventory#112]
hey i wanted to request if you can make the plugin to work with the battlelevels so when you level up for example to level 50 you can use the items im looking forward for this :)

**Comment by OsipXD** [comment]
It is request for LAR or for RPGInventory?

**Comment by KnifeKat** [comment]
He is asking about LoreAttributeRecoded. 

This issue has been resolved/question has been answered in Discord already, and is already capable of doing what he is asking. Speak with Worlfy in the Discord if you wish to ask about LAR @georgegxb , as this is not related to RPGInventory or the Developer of RPGInventory. 

Thank you in advance.
