### ISSUE TITLE
I used "Pay what you what" for RPGInventory on January 02-2018

### ISSUE THREAD

**Issue by TheDuckHunts** [EndlessCodeGroup/RPGInventory#113]
I used "Pay what you what" for RPGInventory on January 02-2018
now it has almost gone a week after you guys Accepted my payment, i've contacted you on Discord, but you just redirect me to OsipXD and Osip hasn't been online ever since someone of you (i might expect it was Osip) accepted my payment. Im feeling like i am getting a very bad response. If i can't contact OsipXD, why does it seems like you are not trying to contact him too???

**Comment by Dereku** [comment]
Because no one knows how to contact him.

**Comment by OsipXD** [comment]
Sorry for this misunderstanding. I was in place where no internet. 
Yes I've accepted your payment but not found any messages on SpigotMC and not added you to buyers list.
Check it now.
