### ISSUE TITLE
Why my rpg inventory icon are full diamond hoe? 

### ISSUE THREAD

**Issue by qaz13570111** [EndlessCodeGroup/RPGInventory#114]
![2018-01-11_02 32 20](https://user-images.githubusercontent.com/35308267/34789052-b31726c6-f677-11e7-80ba-69836524add5.png)

**Comment by OsipXD** [comment]
Hello!
It looks like you misconfigured resource-pack section in config.yml

**Comment by qaz13570111** [comment]
![1](https://user-images.githubusercontent.com/35308267/34835621-4926f5ca-f730-11e7-97bc-05eada32463c.png)
![2](https://user-images.githubusercontent.com/35308267/34835624-4b8f4c5e-f730-11e7-91df-3ce8114e9dff.png)
this is my config.yml,can you help me where is the problem
My plugin:

**Comment by OsipXD** [comment]
You've disabled resource-pack and want fancy inventory?
For this you should use resource-pack that can be downloaded on Overview page of plugin.
