### ISSUE TITLE
The fatal error of the horse

### ISSUE THREAD

**Issue by aaTking** [EndlessCodeGroup/RPGInventory#117]
The fatal error of the horse
Cause the server stuttering
And collapsed

After removing the horse, the problem is solved

**Comment by OsipXD** [comment]
I absolutely not understand you.

1. Please, provide logs
2. Describe bug stepby step.

I just can't reprodice it because it's not described.

**Comment by aaTking** [comment]
I don't know what to say.
There will be no impact when the number of servers is below 20.
When the number of servers is around 35, TPS is very influential.
When the horse is removed, the effect is eliminated.

**Comment by OsipXD** [comment]
And you haven't any errors in logs?

**Comment by aaTking** [comment]
Sorry, there is no log error.
but, /timings Unable to check for more occupancy.
However, before the removal of the horse, TPS =13.
After removing the horse, more than 30 people, TPS =19.8+.
ps: Server memory >10g.

**Comment by OsipXD** [comment]
It's hard to understand for me
