### ISSUE TITLE
Copy the horse's brand bug.

### ISSUE THREAD

**Issue by aaTking** [EndlessCodeGroup/RPGInventory#120]
![image](https://user-images.githubusercontent.com/34217827/35920017-98ecc252-0c51-11e8-8867-665c26fc99a6.png)
When the horse is called on CD.
There is a chance of summoning a horse.

**Comment by OsipXD** [comment]
Can you describe it in details?
A can't reproduce it by your description.

**Comment by aaTking** [comment]
When the player's net speed is not smooth enough, the horse dies, the horse enters the cooldown, and then the call card is likely to be buggy, more and more, to be the object.
To this end, my server has already had an infinite number of horse call CARDS.

**Comment by aaTking** [comment]
Now is very serious,
Pet (Horse) Summon items, unlimited was brush out.

Please urgent repair! Cancel the pet (horse) display the number of cooling can be solved!

**Comment by OsipXD** [comment]
I still can't reproduce it. Cooldown works fine for me and many other users. Do you have any errors in logs?

**Comment by aaTking** [comment]
I ask you to conduct long-term tests on> 50 player servers.
This bug does not happen right away, but when the player's network is delayed.
I also can not detect and provide error logs, but it does exist and has a very serious impact on my server !!

Ask you to set a cooling display switch okay? If no impact on the server do not open.

**Comment by OsipXD** [comment]
As workaround. You can make pets not respawnable.

**Comment by aaTking** [comment]
Is it possible to add an option: Do not show the pet's rebirth of the cooling of the time of death.

PetCountdownPrompt: false/true

**Comment by OsipXD** [comment]
Yes, it's possible and I'l add it maybe. Or fix working of cooldown.

**Comment by aaTking** [comment]
Thank you for listening carefully to my feedback.

**Comment by aaTking** [comment]
![image](https://user-images.githubusercontent.com/34217827/36084836-ff6916e0-0ffb-11e8-89ab-115ee8aa0d4d.png)

**Comment by OsipXD** [comment]
Thanks a lot!

**Comment by aaTking** [comment]
After testing concluded:
When the player pet dies and counts down during cooling down,
Player forced offline
Will have the chance to cool the same number of pets off-line

**Comment by aaTking** [comment]
![image](https://user-images.githubusercontent.com/34217827/36351874-bd282048-14ea-11e8-9e65-a4db7a3359af.png)

bug
