### ISSUE TITLE
Horse Mounting

### ISSUE THREAD

**Issue by doitliketyler** [EndlessCodeGroup/RPGInventory#121]
Hey there. So my players discovered they could mount each other's horses, enter the horse's inventory and remove the saddle and armor.

I'm using the latest versions of Spigot & RPG Inventory.

**Comment by OsipXD** [comment]
Thanks, I'll check it. Do you have errors in logs?

**Comment by doitliketyler** [comment]
No errors whatsoever.

**Comment by OsipXD** [comment]
Ok. I'll try to reproduce it
