### ISSUE TITLE
Re-add old features

### ISSUE THREAD

**Issue by osipxd** [EndlessCodeGroup/RPGInventory#14]
Since 1.3.4 i believe , you removed the equipment book and removed the ability to allow players to join a server without a texture pack.

Please add them back, I feel you are moving away from features that I paid for , for strict usage.  I cannot update to 1.11 because of this. I do not wish to force players to use my intensive texture pack. Many will quit if I do. Also the equipment book was very useful and showed new players easily how to access their equipment.

**Comment by OsipXD** [comment]
Relates to #13
