### ISSUE TITLE
Weird rpg inventory glitch

### ISSUE THREAD

**Issue by Gelox1209** [EndlessCodeGroup/RPGInventory#142]
### Description

Running the server on 1.9 and it seems like whenever I try to open the rpg inventory with the inventory (2x2 crafting grid) it seems that it will randomly select one of the items in the inventory (seems to be only the top half of it) and picks it up
![image](https://user-images.githubusercontent.com/14896896/39387999-cdc4793e-4a31-11e8-9499-1ef9bfc74f83.png)
Like shown above when I clicked on the crafting grid it picked up specifically the glass pane next to the helmet slot.
![image](https://user-images.githubusercontent.com/14896896/39388016-f0233fd8-4a31-11e8-970d-b4c0371b02f0.png)
and when I open it the same way (2x2 crafting grid way) again the glass pane is permanently gone and it picks up another one, and the glass panes will stay gone until I re-log.

Alternatively it seems that the above bug/problem I'm having will not happen at all if I use the command(/rpginv open) to open the inventory.

I am able to recreate this with just using the following plugins:
Latest version of rpginventory
Latest version of Protocollib
Latest version of Via version
Latest version of Vault

Server version:
Spigot 1.9 recommended
Plugin: 2.1.6-PRE

*Weirdest thing is there's*
**No errors in the server logs.**

**Comment by Dereku** [comment]
> Latest version of Via version
ViaVersion can break anything and everywhere even if you do not want it. 
Can you check this "bug" without the ViaVersion?

**Comment by OsipXD** [comment]
Can you provide your logs?

**Comment by Gelox1209** [comment]
How about adding a way to disable opening it from the crafting grid?

**Comment by OsipXD** [comment]
@Gelox1209, it's all messages related to RPGInventory that relates to RPGInventroy?

**Comment by Gelox1209** [comment]
All that it says relating to RPGInventory is..

01.05 17:55:01 [Server] INFO [RPGInventory] Permissions hooked: PermissionsEx
01.05 17:55:01 [Server] INFO [RPGInventory] Economy hooked: Essentials Economy
01.05 17:55:01 [Server] INFO [RPGInventory] Placeholder API hooked!
01.05 17:55:01 [Server] INFO [RPGInventory] Craft extensions isn't loaded.
01.05 17:55:01 [Server] INFO [RPGInventory] Inventory lock system is enabled.
01.05 17:55:01 [Server] INFO [RPGInventory] 4 item(s) has been loaded
01.05 17:55:01 [Server] INFO [RPGInventory] Item system is enabled.
01.05 17:55:01 [Server] INFO [RPGInventory] 6 pet(s) has been loaded
01.05 17:55:01 [Server] INFO [RPGInventory] 1 food(s) has been loaded
01.05 17:55:01 [Server] INFO [RPGInventory] Pet system is enabled.
01.05 17:55:01 [Server] INFO [RPGInventory] 3 backpack type(s) has been loaded
01.05 17:55:01 [Server] INFO [RPGInventory] 0 backpack(s) has been loaded
01.05 17:55:01 [Server] INFO [RPGInventory] Backpack system is enabled.

**Comment by linkinkov** [comment]
I have same bug on version 1.9
Last version were is has not bug - 2.0.8
I cant test it by now, but i think problem is here - https://github.com/EndlessCodeGroup/RPGInventory/commit/f4858465084b5b18a4285660c5de0d6d6a5cdf88
