### ISSUE TITLE
A bug about command "/rpginv bp"

### ISSUE THREAD

**Issue by AndyYu168** [EndlessCodeGroup/RPGInventory#143]
Tested with RPGInventory 2.1.6-PRE, Spigot1.12, Java 8
I enabled it in config.yml and I didn't change any other part of configuration files.

I can see 3 types of backpacks in backpacks.yml, small, medium, large.
However I can't get them as items, when I execute command "**/rpginv bp [name] small**", it shows "Backpack 'small' not found! Use /rpginv bp [player] [ItemId] "
And this is the same for medium and large backpack, no error messages appeared on my console.
Please help me to figure this out, thank you.

**Comment by OsipXD** [comment]
Check in config that backpack system is loaded.

**Comment by AndyYu168** [comment]
[09:42:04] [Server thread/INFO]: [RPGInventory] 3 backpack type(s) has been loaded
[09:42:04] [Server thread/INFO]: [RPGInventory] 0 backpack(s) has been loaded
[09:42:04] [Server thread/INFO]: [RPGInventory] Backpack system is enabled.

There is 0 backpack loaded because I deleted all player data, I'm using a clean server to test it.

**Comment by OsipXD** [comment]
Ok we'll test it.
