### ISSUE TITLE
Dupe on player kick

### ISSUE THREAD

**Issue by a112512514** [EndlessCodeGroup/RPGInventory#146]
* [x] Are you running the latest version?
* [x] Did you check the FAQs on [plugin's page](https://www.spigotmc.org/resources/12498/)?
* [x] Did you check the [Wiki](http://rpginventory.endlesscode.ru/)?
* [x] Did you configure [config.yml](https://github.com/EndlessCodeGroup/RPGInventory/blob/master/src/main/resources/config.yml)?
* [x] Did you perform a cursory search?
* [x] Can you reproduce the problem on clean server (with installed only the plugin and dependencies)?

### Description
Serious bug
When any gui interface works, put items into gui
When the player is dropped, you can double out the material!

Request emergency repairs! This bug has caused serious server problems!

### Steps to Reproduce

1. Open the GUI of other plug-ins (need to put the item's GUI)
2. Put items
3. Dropped (kicked out)
4. Get double items

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Environment

**Server Core:** [Spigot]
**Server Version:** [e.g. 1.12.1]
**Plugin Version:** [e.g. 2.1.6-PRE] ***(YOU SHOULD WRITE VERSION NUMBER, NOT JUST "LATEST")***

***HIGHLY RECOMMENDED TO ATTACH SERVER LOGS TO THE ISSUE!***

**Comment by OsipXD** [comment]
Hello.
Can you add information about your environment and attach server log?

**Comment by a112512514** [comment]
No error, I'm looking for someone to try to fix it

But this is only a temporary act. I hope the author can fix it.

**Comment by OsipXD** [comment]
I can't reproduce it. Please write step-by-step guide again. For example look at this issue: #152 
Every step should be atomic.
