### ISSUE TITLE
Us item requirements from lore

### ISSUE THREAD

**Issue by trungbmt** [EndlessCodeGroup/RPGInventory#148]
please add the level req check on the lore of the item ...
My server is delayed because it, as far as I know, the level req of the item only works if the item is made from the rpginventory plugin, but if I make an item from another plugin then the level req will not work .
So if you can add only the level req check on the item lore then it will be very good.
For example, an item with a lore: "Level Req: 60"
Players must reach level 60 or above to equip them on the rpginventory's PASSIVE slots

Please :'( i really need it

### Environment

**Server Core:** Spigot
**Server Version:** 1.12.2
**Plugin Version:** 2.1.6-PRE

**Comment by OsipXD** [comment]
Hello.
Unfortunately at this moment impossible to use lore for reading item stats and requirements.

**Comment by trungbmt** [comment]
Can it be replaced by an enchant?
For example enchant: Infinity level 15 will require level 15 to equip,
Infinity level 100 then level 100 can equip.
i know this request is not good but i really need it ..

**Comment by trungbmt** [comment]
Or you can do for me an addon like that. I can pay more for it.
