### ISSUE TITLE
Diamond hoes as every item.

### ISSUE THREAD

**Issue by arkobat** [EndlessCodeGroup/RPGInventory#149]
### Prerequisites

* [x] Are you running the latest version?
[21:22:48 INFO]: This server is running CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[21:22:48 INFO]: Checking version, please wait...
[21:22:49 INFO]: You are 83 version(s) behind
Running the latest from this download link: https://getbukkit.org/download/spigot

* [x] Did you check the FAQs on [plugin's page](https://www.spigotmc.org/resources/12498/)?
* [x] Did you check the [Wiki](http://rpginventory.endlesscode.ru/)?
Yes to both.

* [x] Did you configure [config.yml](https://github.com/EndlessCodeGroup/RPGInventory/blob/master/src/main/resources/config.yml)?
Yes. This is my current config: https://hastebin.com/efoqowarud.rb

* [x] Did you perform a cursory search?
Yes, and I've have had written with OsipXD at Discord.

* [x] Can you reproduce the problem on clean server (with installed only the plugin and dependencies)?
Yes, Only using RPGInventory, ProticolLib and Vault.
Reusing the same config

### Description
**Expected behavior:**

All of the items are just diamond hoes.
When I log in, the greeting message from the plugin is sent, as if I have the resource pack correctly installed, and I'm **_not_** kicked.
If I manually download the resourcepack from the link and apply it, the items have the correct look.

### Environment

**Server Core:** Spigot 1.12
**Plugin Version:**  2.1.5
**Server log:** (From the clean server)  https://hastebin.com/oyisexixuc.md

**Comment by Dereku** [comment]
HTTP 406
```
$ wget http://download.kristian-jorgensen.dk/RPGInventory.zip
--2018-05-08 03:36:21--  http://download.kristian-jorgensen.dk/RPGInventory.zip
Resolving download.kristian-jorgensen.dk (download.kristian-jorgensen.dk)... 93.191.156.58
Connecting to download.kristian-jorgensen.dk (download.kristian-jorgensen.dk)|93.191.156.58|:80... connected.
HTTP request sent, awaiting response... 406 Not Acceptable
2018-05-08 03:36:21 ERROR 406: Not Acceptable.
```

**Comment by OsipXD** [comment]
@arkobat, it means that your resourcepack can't be downloaded by Minecraft.

**Comment by arkobat** [comment]
What could cause this?
A port not open at my website?
I’ve uploaded it wrong?

And where should I seek help, is that here, or with my website host? :)

**Comment by OsipXD** [comment]
I think it's problem of host configuration.

**Comment by Arkobat** [comment]
Should have disabled the security now, so wget should work.
Had a friend test it, where he successfully could wget

The problem still occurs. He said that it maybe was because it's own a windows machine the server is hosted?

**Comment by osipxd** [comment]
You calculated wrong hash.\
Right hash is: `aabea95395f073a4e4dc1e8fde2df50c54b94d15`
