### ISSUE TITLE
Use Attributtes instead of current health system.

### ISSUE THREAD

**Issue by OsipXD** [EndlessCodeGroup/RPGInventory#22]
Current Health system so buggy and conflicts with some plugins.
I think, using of Attributes instead of deprecated setMaxHealh/getMaxHealth will resolve it.

**Comment by evernife** [comment]
Suggestion is to use SkillAPI compatibility

I think their is pretty good :D
https://www.spigotmc.org/resources/skillapi.4824/

**Comment by linkinkov** [comment]
Possible use health addition from SkillsPro, Skill Api?

**Comment by OsipXD** [comment]
With attributes? I think, yes.

**Comment by linkinkov** [comment]
Its will be great!
