### ISSUE TITLE
Item dupe bug

### ISSUE THREAD

**Issue by OsipXD** [EndlessCodeGroup/RPGInventory#23]
I think it was due to the save item functionality of your plugin.

1.Put anything in this slot.
![](http://i2.muimg.com/588926/e108f9fe67ebc57f.png)
2.Force the game to be closed using Alt+F4, then re login game.
![](http://i1.piimg.com/588926/7ad4317d7c6ce7ae.png)
The item has been copied..
Any plugin with similar functions is used with your plugin，the BUG will appear.
Please fix it , thank you !

**Comment by OsipXD** [comment]
Thanks, I'll check it. Can you write me name of any plugin with this conflict?

**Comment by VarietyAir** [comment]
RPG Player Leveling , plugins with the same functionality have this BUG。

**Comment by OsipXD** [comment]
Thanks! I'll check it

**Comment by OsipXD** [comment]
I can't reproduce this bug.

**Comment by OsipXD** [comment]
Closed because there no any input
