### ISSUE TITLE
Armor cannot be taken off slots

### ISSUE THREAD

**Issue by Hellcode48** [EndlessCodeGroup/RPGInventory#3]
Please allow a option to take armor off the vanilla slots area, my players are nagging at me all the time about the fact they cant take them off, or add a warning message

**Comment by OsipXD** [comment]
Ok, I'll add it

**Comment by xH3LLRAIZ3Rx** [comment]
thanks :D 

another question: does the backpacks still link with other peoples backpacks? (old issue)

**Comment by OsipXD** [comment]
Sorry, I don't understand your question

**Comment by xH3LLRAIZ3Rx** [comment]
there was a occurring issue where backpacks shared inventories with others, so I would open a backpack and it would show someone elses backpack contents

**Comment by OsipXD** [comment]
All items stores in backpack item and any players can view contents of backpack. I'll add feature to claim items to players.

**Comment by xH3LLRAIZ3Rx** [comment]
could you rather make it where backpacks are private, so they can for example bind their soul to the backpack where no one else can see

**Comment by OsipXD** [comment]
Yes, I plan to add this feature

**Comment by xH3LLRAIZ3Rx** [comment]
ok cool
