### ISSUE TITLE
Heroes Support

### ISSUE THREAD

**Issue by Hellcode48** [EndlessCodeGroup/RPGInventory#35]
I would love to see Heroes support

Plugin Page: https://www.spigotmc.org/resources/heroes-minecraft-rpg-plugin.24734/

Plugin Javadocs: http://www.mediafire.com/?tgw8r3psjmgcrvm

**Comment by OsipXD** [comment]
Already here.
https://github.com/EndlessCodeGroup/RPGInventory/blob/master/src/main/java/ru/endlesscode/rpginventory/utils/PlayerUtils.java#L61

**Comment by xH3LLRAIZ3Rx** [comment]
alright, and since thats in im assuming that the RPGInv custom item stats wont conflict with Heroes attributes system

**Comment by OsipXD** [comment]
Related to #22
