### ISSUE TITLE
Level  Help

### ISSUE THREAD

**Issue by Allenpower** [EndlessCodeGroup/RPGInventory#37]
can support other plugins the Level system?

https://youtu.be/_tjkn2rNxuM << Bug

>>LoreAttributesRecoded (https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-loreattributesrecoded-%E2%97%84%E2%97%84.16177/)

**Comment by OsipXD** [comment]
Other plugins Level Systems already supported.
Your video looks like a conflict.
