### ISSUE TITLE
Add back old GUI system

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [EndlessCodeGroup/RPGInventory#4]
Can you please add back the old GUI system of RPG Inv, because sadly there is some players that cannot run resource packs due to their computers. Please make this a option in the config with the old slot config

**Comment by OsipXD** [comment]
Ok, I'll create non-rp mode back.

**Comment by xH3LLRAIZ3Rx** [comment]
thanks, even though I personally love the resource pack, some players cant even run it

**Comment by xH3LLRAIZ3Rx** [comment]
Can you when you do that also add Skull Texture support for the various items we can make, I wanna use heads for artifacts and such

**Comment by OsipXD** [comment]
Ok

**Comment by OsipXD** [comment]
Already done in 2.0.8
