### ISSUE TITLE
Issue? Unsure.

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#46]
Without RPG inventory, you can be flying on an Elytra, with or without Fireworks...through water. If you're airborne and dive into the water, RPGInv switches your armor automatically. Cancelling your flight. Otherwise you could use fireworks and speed through water. 

Any way to get this to not happen when entering water? Same thing with Lava(If you have Fire resist potion, you could 'fly' through Lava as well.) Or possibly a toggle at least? Thank you!

EDIT: Additionally able to have an option to disable Elytra automatic equipping when tagged in PVP Combat? Players will just fly away during PVP since its super easy to do so. Not absolutely needed, but would love to see this feature implemented.

**Comment by KnifeKat** [comment]
This still occurs if you are not gliding through the water/lava constantly, if you even pause for a moment while sliding through the water, it equips the armor.

Also seems to be an issue with being unable to "Glide" down a set of stairs you are walking down. You're normally able to press spacebar while sliding down a set of ladders, to assume the Gliding position. This is mainly used for Elytra Launchers, this way when you hit the pad, you are jetted up into the air instantly because you're essentially 'gliding' already, and the mechanism shoots you forward at extremely high speeds, allowing you to gain flight with the elytra.

<3

**Comment by OsipXD** [comment]
Oh... I can't think of a way to do it yet. But I'll try

**Comment by OsipXD** [comment]
Can you create separated issue about elytas and stairs?

**Comment by KnifeKat** [comment]
Yeah, It isn't stairs(I used the wrong word): Its for Ladders. I will get you screenshots for it as well, okay? <3 I'll make a new issue in a few hours from now. ^.^
