### ISSUE TITLE
RPGInventory with OpenInv

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#50]
Unsure how to go about this, and getting it to work. Using OpenInv(or any kind of Inventory checker for example), would not work with this Plugin. It sees the original inventory of the player, but anything the player is wearing: Such as Pet, Backpack, and armor/weapons, were not visible. 

Wondering if there is a way to allow OpenInv see the special inventory of RPGInventory?

Please & Thank you.

**Comment by OsipXD** [comment]
Why you're not using command `/rpginv open <player>`?

**Comment by KnifeKat** [comment]
Actually, I wasn't aware of that command. Does this allow you to edit the inventory as well?

Apologies. Testing things out now, including the MYPET thing.

**Comment by OsipXD** [comment]
No, it doesn't allow to edit inventory. But I have in plans to add this function.

**Comment by KnifeKat** [comment]
Yeah, because the only fear I have is people putting items they hacked or stole into their Backpacks, and not letting us Admins get into the backpacks to check the items in there/remove them/see if they been cheating. (Such as XRAY hackers putting the diamonds in the Backpack instead of the Inventory so we can't check if they mined 400 Diamonds in 20min. lol

Stuff like that.

I appreciate your hard work by the way!!!
