### ISSUE TITLE
Elytra Flight & MyPet/Summoning Stone Pet

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#53]
Sorry for all my suggestions/mentions/issues posted here: But here is another one that might make it a big cleaner.

First off I love the new update to the plugin for allowing the Elytra to stay on when touching water.

In regards to Elytra Flight, when you have a Summoning Stone on, and flying through the air, the Summoning Stone's Horse/Puppy/etc mindlessly keeps reappearing next to the player as they fly. While it was fine at first, I found it rather disruptive to constantly see it appear next to me with the reappearing sounds it makes.

Would there be a possibility to toggle that on and off? What I mean is, would there be a way to disable the pet during flight, and once you land, it would reappear again? Would make flight a little cleaner and without the hassle of constantly respawning the pet next to the player.  It would also disable the console from reminding us that the horse is moving wrongly. =P Hehe xD "[17:37:08 WARN]: º6ºlHorse ºf[KnifeKat] moved wrongly!"

Also, Unsure what is causing this error as well with the MyPets. 

[RPGInventory] Plugin RPGInventory v2.1.0 has failed to register events for class ru.endlesscode.rpginventory.pet.mypet.MyPetManager because de/Keyle/MyPet/api/event/MyPetRemoveEvent does not exist.
[17:29:09 INFO]: [RPGInventory] MyPet hooked!

Most favorite Plugin next to CoreProtect! Thanks for all your help and effort in developing something so amazingly awesome! <3

**Comment by OsipXD** [comment]
About this: "de/Keyle/MyPet/api/event/MyPetRemoveEvent does not exist"
You should use MyPet 2.3.2-SNAPSHOT or newer

**Comment by KnifeKat** [comment]
Oh, I was under the impression I was using the newest one. Maybe that one is from the Premium Version? I might have to check it out. <3 It, thanks for your really great support responses, Osip. Its appreciated!!!!!!!!
