### ISSUE TITLE
Bow/Arrow/Totem Slots?

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#54]
Seen someone's texture pack, and it had Bow/Arrow Slots(Can swap to the Bow in the Hotbar and the arrows you have equipped would be the default arrows your bow would shoot. Would be great for when you have more than 1 type of arrows on you, and can just equip the ones you want in your arrow slot.

Would be neat to have this without needing to have to make additional Slots by editing your code(Its Open source I believe, yeah?)

Would be super neat to see this implemented, too.

**Comment by OsipXD** [comment]
As workaround. You can create PASSIVE slot for arrows and sync it with hotbar. But I have in plans to add slots for arrows and others ammo.

**Comment by KnifeKat** [comment]
Might I kindly ask how you'd sync it with the hotbar? I was thinking more along the lines of not needing the arrow in the hotbar to fire the arrows equipped in the passive slot.(Unsure how that would work). Someone in Disord told me about the passive slot for Bows/Arrows. Still trying to get the bows to work, I will check with arrows later on that mark.

**Comment by OsipXD** [comment]
To sync with hotbar use option `quickbar`(for example look at `weapon` slot)

**Comment by KnifeKat** [comment]
Much appreciated. <3
