### ISSUE TITLE
Able to Hurt Horses/Companions with Bows

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#55]
You can damage Horses/Companions with a Bow/Arrow.

Can be done with the Bow in the Offhand, and with the Bow in the Mainhand/anywhere on the main toolbar.

http://imgur.com/a/90N45

Own-pet damage is turned off. I can not hurt it with Weapons like Swords/Axes etc.

attack:
  require-weapon: false
  force-weapon: false
  auto-held: false
  own-pet: false

**Comment by OsipXD** [comment]
So strange because I thought that it was fixed.
Do you have arrors in console?

**Comment by KnifeKat** [comment]
I haven't checked that, I will do that again in the next hour and a half, and show you just in case. I don't think I had any errors, actually.

**Comment by OsipXD** [comment]
Ok, I'll check it tomorrow

**Comment by OsipXD** [comment]
Ok, I'll check it tomorrow

**Comment by OsipXD** [comment]
Reproduced. Fixing now.
