### ISSUE TITLE
Able to disable the "Usage" of an item in RPGInv.

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#56]
Being able to right click to 'use' an item, interferes with quite a bit of plugins.

If I changed the texture to a food item, right clicking/holding would consume/eat it.

Same thing with the Diamond Hoe, right clicking flags another Plugin to use an ability, since the original item is a Diamond Hoe, it tries to activate Herbalisms' effect on MCMMO.

http://imgur.com/a/X0CQr

Wondering if there is a way to disable it at all? Sorry for all these Issues I am posting here, unsure if I am upsetting you by messaging you all these things.

**Comment by OsipXD** [comment]
I thought that it was fixed too... Ok, I'll check it

**Comment by KnifeKat** [comment]
This is why I extensively poke and pry, just makes it better and better since you likely don't have the time to test it down to its nook and cranny. <3

**Comment by OsipXD** [comment]
Thanks for these tests ^)

**Comment by OsipXD** [comment]
I've tested it, but can't reproduce.
My steps:
1. Change `assassin-gloves` texture to `COOKIE`
2. Trying to eat it
3. Nothing happens

Can you provide me step-by-step algorithm

**Comment by KnifeKat** [comment]
I only have this issue when MCMMO is present in the Plugin Folder. Possibly a way that it interacts with objects to allow the use of abilities.

**Comment by OsipXD** [comment]
Try to say about problem to MCMMO author

**Comment by KnifeKat** [comment]
This was User Error and solely the issue of mcMMO. 

Closed & Resolved.
