### ISSUE TITLE
Ability to make Scrolls(Artifacts): Consumable upon Equipping.

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#57]
Example:

I make a Scroll Artifact with multiverse.teleport.nameofworldhere - Player Equips it, and 'Consumes'/'Uses' it, giving them that permission forever unless otherwise removed by other means.

I want players to 'earn' access to other worlds, then be able to use those access door points to teleport to those worlds without them needing the artifact equipped to enter. In the instance they would sell the artifact, or lose it among their belongings...I'd rather the player just be unable to make it optional.

Would prevent players from just selling their Quested Artifact Scrolls after they don't feel they need access to a world anymore. Makes it more valuable to them that they can only equip it once, then its attached forever.

**Comment by OsipXD** [comment]
Good idea. I'll add it
