### ISSUE TITLE
Unable to "Glide" while going down ladders.

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#58]
If you have an Elytra on, you can press space-bar while going down(Or up) ladders to assume the "Gliding" position you take when in flight with the Elytra.

This is generally used for when making Elytra Launchers. Allowing you to be "Gliding" when you hit the entities so you are jettisoned into the air, and not just smack into the ground/a wall because you were not "In Flight" or "Gliding".

This is no longer possible. So made this issue per request from @OsipXD Since I put two issues into a single issue prior. This is to make it a separate issue ~

**Comment by KnifeKat** [comment]
Wouldn't call this an Enhancement, it would be more along the lines of a Bug, actually. Since its already possible in the game.

Here is a video for reference, I have linked to the exact time in the video the usage of the feature is utilizes(Shows its a vanilla feature): https://youtu.be/pbTb71yiQmI?t=67

**Comment by OsipXD** [comment]
Fixed, but now to start glide from ladder you should press `Shift` (sneak).
It's for avoid cases when player been killed on ladder because his armor disappeared.
