### ISSUE TITLE
Blacklist/Whitelist for PETs and MYPETs(If possible) & Per-Pet Permissions?

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#60]
You already have it where Pets and MYPETs can toggle rather they can be used in PVP/PVE, so Admins can control the restriction of pets being used against other players.

However, is there a way to make a Blacklist/whitelist on what -monsters- the pets can, and can not attack? I am unsure how this would work with MYPET Pets, though.

This way a person couldn't get a really strong Wolf for example, and just let it kill the EnderDragon all by itself. Could blacklist the Enderdragon, Endermen, Blazes, and the sort. Also helps with making people not being able to afk mob-grinders either.

That, and if possible, custom monsters by being able to disable it attacking a mob that is named, such as an Enderdragon that is named "Bahamut" for example. I don't know how you could implement this, or if it would be too hard.

Would be helpful for servers using custom mobs, or even MythicMobs as well. Could blacklist people getting a bunch of pets and just swarming a MythicMob or Enderdragon while they run away and do nothing.

Also, if there could be permissions attached to each Pet, and/or possibly MYPETs as well? So you could make people earn the right to use a specific pet, even if they earned a bunch of money and was able to just buy it off someone else. Limits people just avoiding earning a Pet/Horse Summoning Stone(Which everyone is going to fucking want lol).

**Comment by OsipXD** [comment]
Cool ideas, I like it.
