### ISSUE TITLE
Horse Summoning Stone(s): Per-Horse Theme Permission/Display on Egg

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#61]
I know you can change the colors of the Horses, but could the Egg possibly _**display**_ the colors the horse has been assigned with as well? 

Is there a list of supported types of horses to change the colors too? I tried using the chart on this page:

https://minecraft.gamepedia.com/Horse - But to no avail, or, I am inputting the color formats for the horses improperly.

For example: We already have the standard Black/White horse with the Iron Armor, right? The Stone doesn't display that. It just says Horse Summoning Stone.

With the above suggestion, a player could know what the horse looks like in the description of the Summoning Eggstone.

In the instance someone made a bunch of Horse Summoning Stone items in the config, the following would be possible:

Makes it possible for people to trade their horses for other horses. Gives the horses a sense of worth. Players, knowing what color the other person's horse is, could trade their Black/White horse, to maybe a pure white horse, or brown/white horse. Would be neat, wouldn't it? Everyone could actually trade horses as a hobby, or to get one they want.

You might say "People could just tell others what color horse they have, though." or "They could summon it to show the player." While this is true, this allows players who are dishonest to be able to lie to players to get horses they want, by giving away a horse that wasn't as described. Just for the sake of clarity, if anything else, it would be to prevent dishonest players from being dishonest.

If this enhancement/suggestion above was possible, I'd make a bunch of different horses, with a BUNCH of the different color themes for people to pick from.

Also, the other suggestion: Per-Horse Permission. Allowing for a Custom horse permission node. Would be good for VIP/Donor perks(If they wanted). I'd use it to award players the permission to use a special colored horse after completing a quest. Gives players inventive to do a quest, to earn the rights to summon a horse of X color.

You could make a rpginv.horse.<horsecolorpermhere> - That the player could make up their own permission node to add to their Permissions.yml file. Like, the base horse would be rpginv.horse.basic - for example. So anyone can use/equip the basic Horse.

But, if I had a pure white horse, or a white horse with black spots, I could make a node called rpginv.horse.blackspots - and attach that perm to the horse in the pet config file. Then the person that had that Perm, could use the .blackspots horse, as well as the basic one.

I know CrazyAuctions has something like this where its crazyauctions.bid.#   They are Replacing the # with the number of bids a player is allowed to have at any given time. If its crazyauctions.bid.5 it means they can only bid on up to 5 things at once, and so forth. Or they got one that is crazyauctions.auction.# - Does the same thing, but limits the amount of items a player can put on the auction house at any given time.

Players can customize their number here as they place. Unsure if something like this could work with horses.

Potentially a ranking for the horses. Or inheritances. 

rpginv.horse.white
- rpginv.horse.blackspots
- rpginv.horse.brownwhite
   - rpginv.horse.basic

With inheritances, so if you have the .white permission, you have access to -all- the horses, not just the white one. Prevents from having to put allllllll the horses on there.

**Comment by OsipXD** [comment]
As workaround. Now you can configure `color` and `style` of the horse:
```yaml
features:
- "COLOR: DARK_BROWN"
- "STYLE: WHITE"
```
And change `lore` according to this

**Comment by KnifeKat** [comment]
^Oh. I wasn't aware of the Lore being changed. I feel stupid.

What are the supported COLORs and supported STYLES?

I tried:

COLOR: WHITE and STYLE: BLACKSPOTS (since there is white with black spots)-and it didn't seem to work/errored.

Erm I used GREY instead of WHITE. And t here are GREY Horses with Black/brown/white spots.

**Comment by OsipXD** [comment]
Check [this](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Horse.Color.html) and [this](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Horse.Style.html)

**Comment by KnifeKat** [comment]
This is going to be fun to play with, I really like this. Lol.
