### ISSUE TITLE
Stack and Clear Commands

### ISSUE THREAD

**Issue by doitliketyler** [EndlessCodeGroup/RPGInventory#66]
So if I use the /stack command through Worldguard it does this:
https://imgur.com/a/b91rK

and if I use the /clear command in CMI it does this:
https://imgur.com/a/TC28n

Could you please make this so those commands do not work on RPGInventory slots?

**Comment by KnifeKat** [comment]
Oh, nice. Good finds. I don't think this supports CMI right now, though. We'll have to wait for Deku and Osip to reply here to find out. Good job though!

**Comment by OsipXD** [comment]
Oh. Ok, I'll try to add support of theese plugins
