### ISSUE TITLE
Pet Damaged #2

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#69]
No longer happens to horses, but it does happen to Dogs. Unsure if it happens to puppies, however.

https://imgur.com/a/Nzfsa - Suffocates in walls. It appeared in a block after I had equipped the egg. Upon being summoned near a wall/chest/block of any sort, if it catches, it dies.

**Comment by OsipXD** [comment]
So strange. But I can't reproduce this

**Comment by KnifeKat** [comment]
Issue Resolved.

**Comment by KnifeKat** [comment]
Issue Resolved.
