### ISSUE TITLE
Horses Disappear while riding them.

### ISSUE THREAD

**Issue by KnifeKat** [EndlessCodeGroup/RPGInventory#70]
I think this is in relation to the Horses suffocation bug. When you fixed it, I assume you made them just re-spawn outside of the wall. If this is the case, this explains this issue.

When riding a horse, and walking up blocks, chests, or anything that a horse's leg could get potentially 'caught' it, it triggers the horse to disappear and respawn outside the block. I am assuming this is to prevent it from suffocating in a block.

(Wasn't able to ride a horse, because of this. I'd walk up a hill, and if it clipped the hill at all, the horse would despawn and respawn again.)

**Comment by OsipXD** [comment]
Thanks for report. I'll check it

**Comment by OsipXD** [comment]
So strange. I can't reproduce it.

**My steps:**
1. Give horse to player
2. Try to walk up a hill
3. And... nothing happens

**Comment by KnifeKat** [comment]
Here is the config for the pets:

BlackHorse:
    name: "&6&lBlack Horse"
    item-name: "&5&lBlack Horse's Summoning Stone"
    lore:
    - "&e&oPitch Black Horse with a White colored theme."
    item: MONSTER_EGG:Zombie
    type: MOUNT
    health: 100
    speed: 6
    revival: true
    cooldown: 30
    features:
    - "CHEST: FALSE"
    - "ARMOR: DIAMOND_BARDING"
    - "COLOR: BLACK"
    - "STYLE: WHITEFIELD"
  ChestnutHorse:
    name: "&6&lChestnut Horse"
    item-name: "&5&lChestnut Horse's Summoning Stone"
    lore:
    - "&e&oChestnut Horse with a White colored theme."
    item: MONSTER_EGG:Zombie
    type: MOUNT
    health: 100
    speed: 6
    revival: true
    cooldown: 30
    features:
    - "CHEST: FALSE"
    - "ARMOR: DIAMOND_BARDING"
    - "COLOR: CHESTNUT"
    - "STYLE: WHITE_DOTS"

Maybe that will help yas out. ^.^ :)

**Comment by OsipXD** [comment]
Relates to #82
