### ISSUE TITLE
Use 3 slots of vanilla inventory for RPGInv

### ISSUE THREAD

**Issue by trungbmt** [EndlessCodeGroup/RPGInventory#78]
Your plugin uses a gui to store the device and store the player's data in the plugin folder, but I have a lot of bug causing the device to be pulled out of the gui but the data in the folder still exists causing Out the bugs item

Do you know the rekcraft server? They put their jewelry right in the 1,2,3 slots in their stock, this I thought would help me get rid of the bugs that I encountered, would you like to make them look like
It's like your quickbar ... I need it in inventory, and the armor it will be used as usual but no need to click the craft 

sorry, i'm not good at english can cause confusion for you

**Comment by OsipXD** [comment]
This can't be added to 2.x
