### ISSUE TITLE
Plug in error

### ISSUE THREAD

**Issue by mcbaidu** [EndlessCodeGroup/RPGInventory#79]
Crazy brush report wrong
[01:44:17 ERROR]: Could not pass event PlayerMoveEvent to RPGInventory V2.1.2
Org.bukkit.event.EventException
At org.bukkit.plugin.java.JavaPluginLoader$1.execute (JavaPluginLoader.ja)
Va:306) ~[Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At org.bukkit.plugin.RegisteredListener.callEvent (RegisteredListener.jav)
A:62) ~[Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At org.bukkit.plugin.SimplePluginManager.fireEvent (SimplePluginManager.j)
Ava:502) [Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At org.bukkit.plugin.SimplePluginManager.callEvent (SimplePluginManager.j)
Ava:487) [Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At net.minecraft.server.v1_11_R1.PlayerConnection.a (PlayerConnection.jav)
A:615) [Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At net.minecraft.server.v1_11_R1.PacketPlayInFlying.a (SourceFile:126) [S
Pigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition
.a (SourceFile:57) [Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run (SourceFile:)
13) [Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At java.util.concurrent.Executors$RunnableAdapter.call (Unknown Source) [
: 1.8.0_131]
At java.util.concurrent.FutureTask.run (Unknown Source) [?: 1.8.0_131]
At net.minecraft.server.v1_11_R1.SystemUtils.a (SourceFile:46) [Spigot-1.
11.2.jar:git-Spigot-7d78b81-7e19325]
At net.minecraft.server.v1_11_R1.MinecraftServer.D (MinecraftServer.java:)
739) [Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At net.minecraft.server.v1_11_R1.DedicatedServer.D (DedicatedServer.java:)
399) [Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At net.minecraft.server.v1_11_R1.MinecraftServer.C (MinecraftServer.java:)
675) [Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At net.minecraft.server.v1_11_R1.MinecraftServer.run (MinecraftServer.jav)
A:574) [Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
At java.lang.Thread.run (Unknown Source) [?: 1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getWidth () D
At ru.endlesscode.rpginventory.event.listener.ElytraListener.isPlayerCan
Fall (ElytraListener.java:61): ~ ~??]
At ru.endlesscode.rpginventory.event.listener.ElytraListener.onPlayerFal
L (ElytraListener.java:46): ~ ~??]
At sun.reflect.GeneratedMethodAccessor38.invoke (Unknown Source): ~ ~??]
At sun.reflect.DelegatingMethodAccessorImpl.invoke (Unknown Source): 1 ~ ~?
.8.0_131]
At java.lang.reflect.Method.invoke (Unknown Source): 1.8.0_131] ~ ~?
At org.bukkit.plugin.java.JavaPluginLoader$1.execute (JavaPluginLoader.ja)
Va:302) ~[Spigot-1.11.2.jar:git-Spigot-7d78b81-7e19325]
... 15 more

**Comment by Dereku** [comment]
Oh wait, it's 1.11.2.
