### ISSUE TITLE
Pet disappears on high jump

### ISSUE THREAD

**Issue by jxhxnhx** [EndlessCodeGroup/RPGInventory#82]
I found some questions.
1 if owner jump too high ,the pet will disappear until put the pet  into rpg inventory again.
2 Can you update more texture . It's so boring if you see the same texture many times.
Maybe I don't find more texture , Can you list the texture name ？

**Comment by jxhxnhx** [comment]
Your plugin is so good that I can hardly wait to use more prefect plugin.

**Comment by OsipXD** [comment]
I'm not designer and drawing of new textures takes very much time.
