### ISSUE TITLE
Abilities - Equip/Unequip

### ISSUE THREAD

**Issue by doitliketyler** [EndlessCodeGroup/RPGInventory#97]
Could you add 'equip' and 'unequip' to the list of abilities so I can run commands when these actions happen? Since the health system was removed I need a way to add/remove health with certain items. Something that works like the left/right-click abilities do:

```json
abilities:
  equip:
    op: true
    command: "health %PLAYER% add 50"
  unequip
    op: true
    command: "health %PLAYER% take 50"
```

**Comment by linkinkov** [comment]
also for permission
